import { initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getAuth, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { getFirestore, collection, getDocs, addDoc, updateDoc, deleteDoc, doc, getDoc, setDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import { firebaseConfig } from "./firebase-config.js";

const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
// REEMPLAZA este correo por el correo exacto de tu cuenta administradora.
const ADMIN_EMAIL="prismaagency401@gmail.com";
const $=s=>document.querySelector(s);
const msg=(el,text,error=false)=>{el.textContent=text;el.style.color=error?"var(--danger)":"var(--success)"};
const clearForm=()=>{$("#offerId").value="";$("#destination").value="";$("#price").value="";$("#endsAt").value="";$("#active").value="true";$("#msg").textContent=""};
function localInput(iso){if(!iso)return "";const d=new Date(iso);return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,16)}
async function loadOffers(){const box=$("#offerList");box.innerHTML="Cargando...";try{const snap=await getDocs(collection(db,"flashOffers"));const items=snap.docs.map(d=>({id:d.id,...d.data()}));box.innerHTML=items.length?items.map(o=>`<div class="admin-row"><div><strong>${o.destination||""}</strong><br><small>${o.price||""} · ${o.active===false?"Inactiva":"Activa"}${o.endsAt?" · termina "+new Date(o.endsAt).toLocaleString("es-US"):""}</small></div><div class="admin-actions"><button class="btn btn--ghost" data-edit="${o.id}">Editar</button><button class="btn btn--danger" data-del="${o.id}">Eliminar</button></div></div>`).join(""):"No hay ofertas todavía.";box.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>{const o=items.find(x=>x.id===b.dataset.edit);if(!o)return;$("#offerId").value=o.id;$("#destination").value=o.destination||"";$("#price").value=o.price||"";$("#active").value=o.active===false?"false":"true";$("#endsAt").value=localInput(o.endsAt);$("#msg").textContent="Editando: "+(o.destination||"oferta");document.querySelector("#offerForm").scrollIntoView({behavior:"smooth",block:"start"});});box.querySelectorAll("[data-del]").forEach(b=>b.onclick=async()=>{if(confirm("¿Eliminar esta oferta?")){try{await deleteDoc(doc(db,"flashOffers",b.dataset.del));clearForm();msg($("#msg"),"Oferta eliminada.");loadOffers()}catch(e){msg($("#msg"),"No se pudo eliminar la oferta.",true)}}})}catch(e){box.innerHTML="No se pudo leer Firestore. Revisa que la base de datos exista y las reglas estén publicadas."}}
async function loadDeadline(){try{const s=await getDoc(doc(db,"flashSettings","main"));if(s.exists()&&s.data().deadline)$("#deadline").value=localInput(s.data().deadline)}catch{}}
$("#offerForm").onsubmit=async e=>{e.preventDefault();const data={destination:$("#destination").value.trim(),price:$("#price").value.trim(),active:$("#active").value==="true",endsAt:$("#endsAt").value?new Date($("#endsAt").value).toISOString():null,updatedAt:serverTimestamp()};try{const id=$("#offerId").value;if(id)await updateDoc(doc(db,"flashOffers",id),data);else await addDoc(collection(db,"flashOffers"),{...data,createdAt:serverTimestamp()});msg($("#msg"),"Oferta guardada.");clearForm();loadOffers()}catch(e){msg($("#msg"),"No se pudo guardar. Revisa Firestore y sus reglas.",true)}};
$("#clearBtn").onclick=clearForm;
$("#saveDeadline").onclick=async()=>{try{const v=$("#deadline").value;if(!v)throw new Error();await setDoc(doc(db,"flashSettings","main"),{deadline:new Date(v).toISOString(),updatedAt:serverTimestamp()},{merge:true});msg($("#deadlineMsg"),"Contador guardado.")}catch{msg($("#deadlineMsg"),"No se pudo guardar el contador.",true)}};
$("#logoutBtn").onclick=async()=>{await signOut(auth);location.href="login.html"};
onAuthStateChanged(auth,user=>{if(!user||!ADMIN_EMAIL||ADMIN_EMAIL.startsWith("REEMPLAZA_")||user.email.toLowerCase()!==ADMIN_EMAIL.toLowerCase()){document.body.innerHTML='<main class="admin-denied card-surface"><h2>Acceso denegado</h2><p>Configura el correo administrador en admin.js y entra con esa cuenta.</p><a class="btn btn--primary" href="login.html">Ir al acceso</a></main>';return}$("#adminUser").textContent="Administrador: "+user.email;loadOffers();loadDeadline()});
